import type {
  AdminUser,
  BlogPostItem,
  ContactInquiry,
  CoreValueCMS,
  FaqItemCMS,
  FeaturedCaseStudyCMS,
  KeyMetricCMS,
  PageConfig,
  ProjectItem,
  SectionConfig,
  ServiceCaseCMS,
  ServiceItem,
  SiteSettings,
  TeamMemberItem,
  TimelineMilestoneCMS,
  WorkResultCMS,
} from "@/types/cms";

export interface CMSDataStore {
  siteSettings: SiteSettings;
  pagesConfig: Record<string, PageConfig>;
  sectionConfigs: Record<string, SectionConfig>;
  services: ServiceItem[];
  projects: ProjectItem[];
  teamMembers: TeamMemberItem[];
  blogPosts: BlogPostItem[];
  faqs: FaqItemCMS[];
  timelineMilestones: TimelineMilestoneCMS[];
  coreValues: CoreValueCMS[];
  serviceCases: ServiceCaseCMS[];
  workResults: WorkResultCMS[];
  keyMetrics: KeyMetricCMS[];
  featuredCaseStudy: FeaturedCaseStudyCMS;
  contactInquiries: ContactInquiry[];
  adminUsers: AdminUser[];
}

export const initialCMSStore: CMSDataStore = {
  siteSettings: {
    id: "default",
    siteName: "Catalyst Digital",
    tagline: "A Software Development Studio building practical, scalable solutions for real operational challenges.",
    primaryEmail: "ceo@catalystdigitals.com",
    supportEmail: "hceo@catalystdigitals.com",
    phone: "+94 72 280 0104",
    headquarters: "Colombo, Sri Lanka",
    officeAddress1: "Colombo",
    officeAddress2: "Sri Lanka",
    linkedinUrl: "https://www.linkedin.com/company/catalyst-digital",
    maintenanceMode: false,
    maintenanceTitle: "Platform Under Scheduled Maintenance",
    maintenanceMessage: "We are deploying performance enhancements and updates. Our team will be back online shortly.",
    updatedAt: "2026-09-14T00:00:00Z",
  },
  pagesConfig: {
    home: {
      slug: "home",
      title: "Home",
      isActive: true,
      displayOrder: 1,
      offlineMessage: "The Home portal is undergoing scheduled infrastructure upgrades. Please check back shortly.",
      updatedAt: "2026-09-14T00:00:00Z",
    },
    services: {
      slug: "services",
      title: "Services",
      isActive: true,
      displayOrder: 2,
      offlineMessage: "Our Services catalog is currently undergoing a capability revamp. Contact us directly for active service packages.",
      updatedAt: "2026-09-14T00:00:00Z",
    },
    work: {
      slug: "work",
      title: "Work",
      isActive: true,
      displayOrder: 3,
      offlineMessage: "Our portfolio case study showcase is temporarily offline while we update client engagement records.",
      updatedAt: "2026-09-14T00:00:00Z",
    },
    about: {
      slug: "about",
      title: "About",
      isActive: true,
      displayOrder: 4,
      offlineMessage: "The company background page is momentarily unavailable.",
      updatedAt: "2026-09-14T00:00:00Z",
    },
    blog: {
      slug: "blog",
      title: "Blog",
      isActive: true,
      displayOrder: 5,
      offlineMessage: "The insights and technical publication feed is currently offline.",
      updatedAt: "2026-09-14T00:00:00Z",
    },
    contact: {
      slug: "contact",
      title: "Contact",
      isActive: true,
      displayOrder: 6,
      offlineMessage: "Inbound messaging is temporarily paused. Please reach out to ceo@catalystdigitals.com directly.",
      updatedAt: "2026-09-14T00:00:00Z",
    },
  },
  sectionConfigs: {
    home_hero: {
      id: "home_hero",
      pageSlug: "home",
      sectionKey: "hero",
      sectionName: "Hero Introduction",
      isActive: true,
      eyebrow: "Digital product partner",
      heading: "Build reliable digital experiences with Catalyst Digital",
      subheading: "A Software Development Studio building practical, scalable solutions for real operational challenges.",
      displayOrder: 1,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    home_stats: {
      id: "home_stats",
      pageSlug: "home",
      sectionKey: "stats",
      sectionName: "Key Performance Metrics",
      isActive: true,
      displayOrder: 2,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    home_services: {
      id: "home_services",
      pageSlug: "home",
      sectionKey: "services",
      sectionName: "Services Overview",
      isActive: true,
      eyebrow: "Services",
      heading: "Cross-functional teams to ship faster",
      subheading: "From strategy to scale, we bring product, design, and engineering under one delivery model.",
      displayOrder: 3,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    home_team: {
      id: "home_team",
      pageSlug: "home",
      sectionKey: "team",
      sectionName: "Leadership Team Preview",
      isActive: true,
      eyebrow: "Our Team",
      heading: "Senior specialists focused on outcomes",
      subheading: "Work directly with strategists, designers, and engineers who stay close to your product goals.",
      displayOrder: 4,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    home_clients: {
      id: "home_clients",
      pageSlug: "home",
      sectionKey: "clients",
      sectionName: "Tech Stack Capabilities",
      isActive: true,
      heading: "TECH STACK WE WORK WITH",
      displayOrder: 5,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    home_cta: {
      id: "home_cta",
      pageSlug: "home",
      sectionKey: "cta",
      sectionName: "Call to Action Conversion Banner",
      isActive: true,
      eyebrow: "Ready to build?",
      heading: "Let's launch your next digital product with confidence.",
      subheading: "Tell us what you are building, where you are blocked, and the momentum you need next.",
      displayOrder: 6,
      updatedAt: "2026-09-14T00:00:00Z",
    },

    services_hero: {
      id: "services_hero",
      pageSlug: "services",
      sectionKey: "services_hero",
      sectionName: "Services Hero",
      isActive: true,
      eyebrow: "Our Expertise",
      heading: "Scalable solutions for modern enterprises",
      subheading: "We combine deep technical expertise with strategic thinking to build software that works at scale. Explore our core service offerings.",
      displayOrder: 1,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    services_grid: {
      id: "services_grid",
      pageSlug: "services",
      sectionKey: "services_grid",
      sectionName: "Services Catalog Grid",
      isActive: true,
      displayOrder: 2,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    services_in_action: {
      id: "services_in_action",
      pageSlug: "services",
      sectionKey: "services_in_action",
      sectionName: "Services In Action (Case Snapshots)",
      isActive: true,
      eyebrow: "Case Snapshots",
      heading: "Services in action",
      subheading: "See how we apply these capabilities to solve real-world challenges for growth-stage teams.",
      displayOrder: 3,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    services_cta: {
      id: "services_cta",
      pageSlug: "services",
      sectionKey: "cta",
      sectionName: "Services CTA Banner",
      isActive: true,
      eyebrow: "Ready to build?",
      heading: "Let's launch your next digital product with confidence.",
      subheading: "Tell us what you are building, where you are blocked, and the momentum you need next.",
      displayOrder: 4,
      updatedAt: "2026-09-14T00:00:00Z",
    },

    work_hero: {
      id: "work_hero",
      pageSlug: "work",
      sectionKey: "work_hero",
      sectionName: "Work Portfolio Hero",
      isActive: true,
      eyebrow: "Case Studies",
      heading: "Our impact in action",
      subheading: "We do not just ship code. We solve business challenges with engineering excellence and measurable outcomes.",
      displayOrder: 1,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    work_filters: {
      id: "work_filters",
      pageSlug: "work",
      sectionKey: "work_filters",
      sectionName: "Category Filter Bar",
      isActive: true,
      displayOrder: 2,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    work_grid: {
      id: "work_grid",
      pageSlug: "work",
      sectionKey: "work_grid",
      sectionName: "Projects Catalog Grid",
      isActive: true,
      displayOrder: 3,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    work_case_study: {
      id: "work_case_study",
      pageSlug: "work",
      sectionKey: "work_case_study",
      sectionName: "Featured Transformation Case Study",
      isActive: true,
      eyebrow: "Featured transformation",
      heading: "Revolutionizing LogiCore Global Infrastructure",
      subheading: "We redesigned the backbone of a multi-region platform to improve reliability, delivery speed, and global operational visibility.",
      displayOrder: 4,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    work_results: {
      id: "work_results",
      pageSlug: "work",
      sectionKey: "work_results",
      sectionName: "Engineering Value Pillars",
      isActive: true,
      displayOrder: 5,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    work_cta: {
      id: "work_cta",
      pageSlug: "work",
      sectionKey: "cta",
      sectionName: "Work CTA Banner",
      isActive: true,
      eyebrow: "Ready to build?",
      heading: "Let's launch your next digital product with confidence.",
      subheading: "Tell us what you are building, where you are blocked, and the momentum you need next.",
      displayOrder: 6,
      updatedAt: "2026-09-14T00:00:00Z",
    },

    about_hero: {
      id: "about_hero",
      pageSlug: "about",
      sectionKey: "about_hero",
      sectionName: "About Us Hero",
      isActive: true,
      eyebrow: "Who We Are",
      heading: "Empowering businesses through purpose-built technology.",
      subheading: "We are Catalyst Digital, a product and engineering partner that helps teams move from ideas to measurable outcomes with confidence.",
      displayOrder: 1,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    about_journey: {
      id: "about_journey",
      pageSlug: "about",
      sectionKey: "journey",
      sectionName: "Company Journey & Timeline",
      isActive: true,
      heading: "Our journey",
      subheading: "How we evolved from a focused team into a trusted product partner.",
      displayOrder: 2,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    about_team: {
      id: "about_team",
      pageSlug: "about",
      sectionKey: "team",
      sectionName: "Full Team Showcase",
      isActive: true,
      eyebrow: "Team",
      heading: "The minds behind the mission",
      subheading: "Cross-functional experts in strategy, design, and engineering, aligned around meaningful outcomes.",
      displayOrder: 3,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    about_values: {
      id: "about_values",
      pageSlug: "about",
      sectionKey: "values",
      sectionName: "Core Organizational Values",
      isActive: true,
      heading: "Our core values",
      subheading: "Principles that shape how we build, collaborate, and make decisions every day.",
      displayOrder: 4,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    about_stats: {
      id: "about_stats",
      pageSlug: "about",
      sectionKey: "stats",
      sectionName: "Operational Scale Achievements",
      isActive: true,
      displayOrder: 5,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    about_cta: {
      id: "about_cta",
      pageSlug: "about",
      sectionKey: "cta",
      sectionName: "About CTA Banner",
      isActive: true,
      eyebrow: "Ready to build?",
      heading: "Let's launch your next digital product with confidence.",
      subheading: "Tell us what you are building, where you are blocked, and the momentum you need next.",
      displayOrder: 6,
      updatedAt: "2026-09-14T00:00:00Z",
    },

    blog_hero: {
      id: "blog_hero",
      pageSlug: "blog",
      sectionKey: "blog_hero",
      sectionName: "Blog & Insights Hero",
      isActive: true,
      eyebrow: "Latest Updates",
      heading: "Our insights",
      subheading: "Thoughts, patterns, and lessons from our work across design, engineering, and digital delivery.",
      displayOrder: 1,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    blog_featured: {
      id: "blog_featured",
      pageSlug: "blog",
      sectionKey: "blog_featured",
      sectionName: "Featured Post Slot",
      isActive: true,
      heading: "Featured post",
      displayOrder: 2,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    blog_grid: {
      id: "blog_grid",
      pageSlug: "blog",
      sectionKey: "blog_grid",
      sectionName: "Recent Articles Grid",
      isActive: true,
      heading: "Recent articles",
      displayOrder: 3,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    blog_sidebar: {
      id: "blog_sidebar",
      pageSlug: "blog",
      sectionKey: "blog_sidebar",
      sectionName: "Blog Sidebar & Widgets",
      isActive: true,
      displayOrder: 4,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    blog_load_more: {
      id: "blog_load_more",
      pageSlug: "blog",
      sectionKey: "blog_load_more",
      sectionName: "Pagination / Load More",
      isActive: true,
      displayOrder: 5,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    blog_cta: {
      id: "blog_cta",
      pageSlug: "blog",
      sectionKey: "cta",
      sectionName: "Blog CTA Banner",
      isActive: true,
      eyebrow: "Ready to build?",
      heading: "Let's launch your next digital product with confidence.",
      subheading: "Tell us what you are building, where you are blocked, and the momentum you need next.",
      displayOrder: 6,
      updatedAt: "2026-09-14T00:00:00Z",
    },

    contact_hero: {
      id: "contact_hero",
      pageSlug: "contact",
      sectionKey: "contact_hero",
      sectionName: "Contact Hero",
      isActive: true,
      eyebrow: "Get in touch",
      heading: "Let's turn your vision into reality.",
      subheading: "Have a complex problem or a bold idea? Our experts are ready to jump in and start building.",
      displayOrder: 1,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    contact_form: {
      id: "contact_form",
      pageSlug: "contact",
      sectionKey: "contact_form",
      sectionName: "Client Message Form",
      isActive: true,
      heading: "Send us a message",
      subheading: "Share your goals. We usually reply within one business day.",
      displayOrder: 2,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    contact_details: {
      id: "contact_details",
      pageSlug: "contact",
      sectionKey: "contact_details",
      sectionName: "Direct Communication Channels",
      isActive: true,
      heading: "Contact Details",
      displayOrder: 3,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    contact_office: {
      id: "contact_office",
      pageSlug: "contact",
      sectionKey: "contact_office",
      sectionName: "Physical Headquarters Card",
      isActive: true,
      heading: "Find us",
      displayOrder: 4,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    contact_trust: {
      id: "contact_trust",
      pageSlug: "contact",
      sectionKey: "contact_trust",
      sectionName: "Social Proof Trust Badge",
      isActive: true,
      heading: "Trusted by 200+ companies",
      subheading: "From high-growth startups to Fortune 500 enterprises.",
      displayOrder: 5,
      updatedAt: "2026-09-14T00:00:00Z",
    },
    contact_faq: {
      id: "contact_faq",
      pageSlug: "contact",
      sectionKey: "contact_faq",
      sectionName: "Common Questions Accordion",
      isActive: true,
      heading: "Common questions",
      subheading: "Everything you need to know before working with us.",
      displayOrder: 6,
      updatedAt: "2026-09-14T00:00:00Z",
    },
  },
  services: [
    {
      id: "srv-01",
      slug: "product-engineering",
      title: "Product Engineering",
      description: "Design and build resilient web products with modern architecture and clean delivery loops.",
      icon: "Code2",
      isActive: true,
      displayOrder: 1,
    },
    {
      id: "srv-02",
      slug: "ui-ux-design",
      title: "UI/UX Design",
      description: "Craft intuitive interfaces and design systems that improve conversion and reduce user friction.",
      icon: "Palette",
      isActive: true,
      displayOrder: 2,
    },
    {
      id: "srv-03",
      slug: "cloud-devops",
      title: "Cloud & DevOps",
      description: "Automate infrastructure, deployments, and observability to keep platforms fast and stable.",
      icon: "Cloud",
      isActive: true,
      displayOrder: 3,
    },
    {
      id: "srv-04",
      slug: "data-ai-solutions",
      title: "Data & AI Solutions",
      description: "Turn business data into decisions with analytics pipelines, dashboards, and applied AI workflows.",
      icon: "Bot",
      isActive: true,
      displayOrder: 4,
    },
    {
      id: "srv-05",
      slug: "qa-automation",
      title: "QA Automation",
      description: "Scale testing with reliable automation suites that catch regressions before customers do.",
      icon: "ShieldCheck",
      isActive: true,
      displayOrder: 5,
    },
    {
      id: "srv-06",
      slug: "growth-optimization",
      title: "Growth Optimization",
      description: "Improve funnel performance through experimentation, technical SEO, and conversion-focused updates.",
      icon: "TrendingUp",
      isActive: true,
      displayOrder: 6,
    },
  ],
  projects: [
    {
      id: "prj-01",
      slug: "finstream-wealth-platform",
      title: "FinStream: AI-powered Wealth Platform",
      description: "Portfolio forecasting and automated advisory workflows for modern investment teams.",
      tags: ["AI", "Web"],
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
      isActive: true,
      displayOrder: 1,
    },
    {
      id: "prj-02",
      slug: "ecodrive-logistics-optimization",
      title: "EcoDrive: Global Logistics Optimization",
      description: "Operational intelligence for cross-region fleet planning and route efficiency.",
      tags: ["Cloud", "Data"],
      image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80",
      isActive: true,
      displayOrder: 2,
    },
    {
      id: "prj-03",
      slug: "healthsync-patient-portal",
      title: "HealthSync: Interoperable Patient Portal",
      description: "Secure care coordination experience with unified records and messaging flows.",
      tags: ["Mobile", "Security"],
      image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80",
      isActive: true,
      displayOrder: 3,
    },
    {
      id: "prj-04",
      slug: "nexa-commerce-enterprise-eshop",
      title: "Nexa Commerce: Enterprise E-shop",
      description: "High-throughput commerce platform with optimized checkout and catalog pipelines.",
      tags: ["Web", "API"],
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
      isActive: true,
      displayOrder: 4,
    },
    {
      id: "prj-05",
      slug: "datavault-ledger-security",
      title: "DataVault: Distributed Ledger Security",
      description: "Tamper-resistant audit rails and trust infrastructure for regulated operations.",
      tags: ["Blockchain", "Security"],
      image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
      isActive: true,
      displayOrder: 5,
    },
    {
      id: "prj-06",
      slug: "aura-creative-portfolio",
      title: "Aura: Creative Portfolio Experience",
      description: "Content-first digital platform with interactive storytelling and fast delivery.",
      tags: ["Design", "Web"],
      image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
      isActive: true,
      displayOrder: 6,
    },
  ],
  teamMembers: [
    {
      id: "tm-01",
      name: "Ashoka Jayasinghe",
      role: "CEO & Co-founder",
      image: "https://media.licdn.com/dms/image/v2/C5103AQE0c9drmB6x3Q/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1531893469759?e=2147483647&v=beta&t=FWCjtqz5l7dbDzhSHsHgjF2rfM_S90yg7SW2e30BHaU",
      linkedin: "https://www.linkedin.com/in/ashoka-jayasinghe-89b4b5258/",
      isActive: true,
      displayOrder: 1,
    },
    {
      id: "tm-02",
      name: "Aruna Jalath",
      role: "CTO & Co-founder",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&h=400&q=80",
      linkedin: "https://www.linkedin.com/in/aruna-jalath-7a41a363/?originalSubdomain=lk",
      isActive: true,
      displayOrder: 2,
    },
    {
      id: "tm-03",
      name: "ZylosCode",
      role: "CDO & Co-founder",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=400&q=80",
      linkedin: "https://www.linkedin.com/in/zylos-code-069408403/",
      isActive: true,
      displayOrder: 3,
    },
    {
      id: "tm-04",
      name: "Thilini Karunaratne",
      role: "COO",
      image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&h=400&q=80",
      linkedin: "https://www.linkedin.com/in/thilini-karunaratne-857895362/?originalSubdomain=lk",
      isActive: true,
      displayOrder: 4,
    },
  ],
  blogPosts: [
    {
      id: "post-01",
      slug: "building-scalable-cloud-platforms-in-2026",
      title: "Architecting Scalable Cloud Platforms in 2026",
      excerpt: "Key patterns for building decoupled, high-resilience systems that survive cross-region failovers.",
      content: "Modern digital systems demand proactive reliability, observability, and decoupled micro-architectures...",
      author: "Aruna Jalath",
      date: "Sep 10, 2026",
      tags: ["Cloud", "Architecture", "DevOps"],
      coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
      isPublished: true,
      isFeatured: true,
    },
  ],
  faqs: [
    {
      id: "faq-01",
      question: "What is your typical project timeline?",
      answer: "Most projects launch between 6 to 12 weeks depending on scope. We define milestones early and share weekly progress.",
      isActive: true,
      displayOrder: 1,
    },
    {
      id: "faq-02",
      question: "How do you handle project pricing?",
      answer: "We use scoped delivery plans with transparent estimates. Engagements can be fixed-scope, retainer, or phased delivery.",
      isActive: true,
      displayOrder: 2,
    },
    {
      id: "faq-03",
      question: "What technologies do you specialize in?",
      answer: "Our teams work across modern web platforms, cloud infrastructure, automation, and AI-enabled product workflows.",
      isActive: true,
      displayOrder: 3,
    },
    {
      id: "faq-04",
      question: "Do you offer post-launch support?",
      answer: "Yes. We provide monitoring, maintenance, optimization, and roadmap support after launch based on your needs.",
      isActive: true,
      displayOrder: 4,
    },
  ],
  timelineMilestones: [
    {
      id: "tm-1",
      year: "2018",
      title: "Founded with a Product-first Vision",
      description: "We started as a small engineering team focused on solving difficult business problems with clarity.",
      isActive: true,
      displayOrder: 1,
    },
    {
      id: "tm-2",
      year: "2020",
      title: "Expanded to Global Delivery",
      description: "Our remote-first model allowed us to deliver cross-border projects with faster feedback loops.",
      isActive: true,
      displayOrder: 2,
    },
    {
      id: "tm-3",
      year: "2022",
      title: "Scaled Multi-domain Expertise",
      description: "We broadened capabilities across cloud, data, and product design for enterprise clients.",
      isActive: true,
      displayOrder: 3,
    },
    {
      id: "tm-4",
      year: "2025",
      title: "AI-native Product Delivery",
      description: "We integrated AI-driven workflows into our process to speed up decisions and delivery quality.",
      isActive: true,
      displayOrder: 4,
    },
  ],
  coreValues: [
    {
      id: "val-1",
      title: "Ownership",
      description: "We treat every product challenge as our own and stay accountable from discovery to delivery.",
      isActive: true,
      displayOrder: 1,
    },
    {
      id: "val-2",
      title: "Clarity",
      description: "We simplify complexity through strong communication, structured thinking, and transparent process.",
      isActive: true,
      displayOrder: 2,
    },
    {
      id: "val-3",
      title: "Integrity",
      description: "We prioritize long-term trust over short-term wins in both technical decisions and partnerships.",
      isActive: true,
      displayOrder: 3,
    },
  ],
  serviceCases: [
    {
      id: "sc-1",
      category: "Web Dev",
      title: "Real-time Portfolio Tracker",
      resultTag: "40% faster insights",
      isActive: true,
      displayOrder: 1,
    },
    {
      id: "sc-2",
      category: "Mobile",
      title: "Patient Monitoring App",
      resultTag: "95% less latency",
      isActive: true,
      displayOrder: 2,
    },
    {
      id: "sc-3",
      category: "Cloud",
      title: "Automated Supply Hub",
      resultTag: "67% cost reduction",
      isActive: true,
      displayOrder: 3,
    },
    {
      id: "sc-4",
      category: "AI",
      title: "Predictive Inventory",
      resultTag: "32% efficiency gain",
      isActive: true,
      displayOrder: 4,
    },
  ],
  workResults: [
    {
      id: "wr-1",
      title: "Clean Architecture",
      description: "Maintainable system boundaries that reduce long-term complexity and change cost.",
      isActive: true,
      displayOrder: 1,
    },
    {
      id: "wr-2",
      title: "Performance First",
      description: "Measured optimization across rendering, delivery, and runtime bottlenecks.",
      isActive: true,
      displayOrder: 2,
    },
    {
      id: "wr-3",
      title: "Data-driven Results",
      description: "Product decisions guided by instrumentation, experiments, and business KPIs.",
      isActive: true,
      displayOrder: 3,
    },
  ],
  keyMetrics: [
    { id: "home_projects", context: "home", label: "Projects Delivered", value: 120, suffix: "+", isActive: true, displayOrder: 1 },
    { id: "home_clients", context: "home", label: "Clients Supported", value: 65, suffix: "+", isActive: true, displayOrder: 2 },
    { id: "home_retention", context: "home", label: "Client Retention", value: 96, suffix: "%", isActive: true, displayOrder: 3 },
    { id: "home_experience", context: "home", label: "Years of Experience", value: 8, suffix: "+", isActive: true, displayOrder: 4 },
    { id: "about_projects", context: "about", label: "Projects", value: 150, suffix: "+", isActive: true, displayOrder: 1 },
    { id: "about_hours", context: "about", label: "Build Hours", value: 45, suffix: "k", isActive: true, displayOrder: 2 },
    { id: "about_team", context: "about", label: "Team Members", value: 12, suffix: "+", isActive: true, displayOrder: 3 },
    { id: "about_satisfaction", context: "about", label: "Client Satisfaction", value: 98, suffix: "%", isActive: true, displayOrder: 4 },
  ],
  featuredCaseStudy: {
    id: "primary",
    eyebrow: "Featured transformation",
    title: "Revolutionizing LogiCore Global Infrastructure",
    description: "We redesigned the backbone of a multi-region platform to improve reliability, delivery speed, and global operational visibility.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    ctaHref: "/work/logicore-global-infrastructure",
    metric1Label: "Efficiency Increase",
    metric1Value: "40%",
    metric2Label: "Platform Uptime",
    metric2Value: "99.99%",
  },
  contactInquiries: [
    {
      id: "inq-01",
      name: "Marcus Vance",
      email: "marcus@vancecap.io",
      company: "Vance Capital",
      message: "We need to modernize our wealth forecasting portal with AI integrations. Interested in scoping a 10-week MVP.",
      status: "new",
      createdAt: "2026-09-14T09:15:00Z",
    },
  ],
  adminUsers: [
    {
      id: "usr-super-admin-01",
      email: "superadmin@catalystdigital.com",
      fullName: "Ashoka Jayasinghe (CEO)",
      roleId: "super_admin",
      isActive: true,
      createdAt: "2026-01-01T00:00:00Z",
    },
    {
      id: "usr-content-admin-02",
      email: "content@catalystdigital.com",
      fullName: "ZylosCode (CDO)",
      roleId: "content_admin",
      isActive: true,
      createdAt: "2026-01-01T00:00:00Z",
    },
    {
      id: "usr-editor-03",
      email: "editor@catalystdigital.com",
      fullName: "Thilini Karunaratne (COO)",
      roleId: "editor",
      isActive: true,
      createdAt: "2026-01-01T00:00:00Z",
    },
    {
      id: "usr-viewer-04",
      email: "auditor@catalystdigital.com",
      fullName: "Security Compliance Auditor",
      roleId: "viewer",
      isActive: true,
      createdAt: "2026-01-01T00:00:00Z",
    },
  ],
};
